name: postal_code_jp
author: Kazuki Yamaguchi <y.kazuki0614n@gmail.com>
version: 1.2.0
homepage: https://github.com/yamarkz/postal_code_jp
description: A dart package for Japan Post official postal code, a.k.a zip code, search and update.
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  sqflite: 2.0.2
  flutter:
    sdk: flutter


  flutter_localizations: # Add this line
    sdk: flutter
dev_dependencies: 
  test: ^1.17.4



flutter:
  assets:
    - database/zip.db
